name: Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js to publish to npm
      uses: actions/setup-node@v4
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.com'

    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-cache-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies
      run: yarn

    - name: Run tests
      run: |
        yarn lint
        yarn test

    - name: Get package version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master

    - name: Get changelog
      id: changelog
      uses: mindsers/changelog-reader-action@v2
      with:
        version: ${{ steps.package-version.outputs.current-version }}

    - name: Publish npm package
      run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Setup Node.js to publish to GitHub Packages
      uses: actions/setup-node@v4
      with:
        node-version: '16.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@smartbear'

    - name: Create GitHub release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.package-version.outputs.current-version }}
        release_name: v${{ steps.package-version.outputs.current-version }}
        body: ${{ steps.changelog.outputs.changes }}

    - name: Publish GitHub package
      run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
